backend:
  name: github
  repo: moop0804/mfn-rights.github.io
  branch: main
  base_url: https://crimson-bush-c3a7.dai-lee.workers.dev

media_folder: "photos"
public_folder: "/photos"

collections:
  - name: "posts"
    label: "게시글 작성하기"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "게시판 선택 (activities 또는 statements 입력)", name: "categories", widget: "string"}
      - {label: "머리말 (자료집, 캠페인, 성명, 논평 등)", name: "badge", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문 내용", name: "body", widget: "markdown"}
